# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Post:
  fields:
    default: number, subject, from, time, ancestry
    form: number, subject, from, time, body, ancestry
  order_by: 
  relationships: translations
  filters: 
  search: 
  application: dev-ruby

Translation:
  fields:
    default: post_id, user_id, post
    form: post_id, user_id, body, post
  order_by: 
  relationships: post, user
  filters: 
  search: 
  application: dev-ruby

User:
  fields:
    default: provider, uid, name
    form: provider, uid, name
  order_by: 
  relationships: translations
  filters: 
  search: name
  application: dev-ruby

